name : couchdb

uuid : bb83c747-1d7b-4bc1-bc01-d2fef4c6cb5d

description : "python binding for couchdb"
authors : [couchdb-python]
config_version : 0
version : 1.0.0

commands:
- export PYCOUCHDB=$BD_SOFTS/couchdb-python/!VERSION!
- export PYTHONPATH=$PYCOUCHDB:$PYTHONPATH
