name : pycouchdb

uuid : bb83c747-1d7b-4bc1-bc01-d2fef4c6cb5d

description : "python binding for couchdb"
authors : [couchdb-python]
config_version : 0
version : 0.9.0

#requires :
#- anytool

commands:
- export PYCOUCHDBVER=0.9.0
- export PYCOUCHDB=!ROOT!/src
- export PYTHONPATH=$PYCOUCHDB:$PYTHONPATH
